insert into Products (id, title, price) values (1, 'Food - Oils & Vinegars', 3.99);
insert into Products (id, title, price) values (2, 'Food - Produce', 3.49);
insert into Products (id, title, price) values (3, 'Food - Condiments', 3.99);
insert into Products (id, title, price) values (4, 'Clothing - Bottoms', 29.99);
insert into Products (id, title, price) values (5, 'Office', 8.99);
insert into Products (id, title, price) values (6, 'Food - Snacks', 3.49);
insert into Products (id, title, price) values (7, 'Food - Frozen', 8.99);
insert into Products (id, title, price) values (8, 'Food - Grains', 2.29);
insert into Products (id, title, price) values (9, 'Kitchen', 89.99);
insert into Products (id, title, price) values (10, 'Food - Sauces', 4.79);
insert into Products (id, title, price) values (11, 'Food - Condiments', 2.79);
insert into Products (id, title, price) values (12, 'Food - Snacks', 3.99);
insert into Products (id, title, price) values (13, 'Food - Grains', 2.39);
insert into Products (id, title, price) values (14, 'Pets', 44.99);
insert into Products (id, title, price) values (15, 'Home', 19.99);
insert into Products (id, title, price) values (16, 'Food - Breakfast', 4.49);
insert into Products (id, title, price) values (17, 'Food - Dairy Alternatives', 1.99);
insert into Products (id, title, price) values (18, 'Home', 29.99);
insert into Products (id, title, price) values (19, 'Food - Condiments', 3.79);
insert into Products (id, title, price) values (20, 'Food - Condiments', 1.99);
insert into Products (id, title, price) values (21, 'Food - Breakfast', 3.29);
insert into Products (id, title, price) values (22, 'Kitchen', 19.99);
insert into Products (id, title, price) values (23, 'Food - Frozen Foods', 4.99);
insert into Products (id, title, price) values (24, 'Food - Condiments', 2.99);
insert into Products (id, title, price) values (25, 'Outdoor', 24.99);
insert into Products (id, title, price) values (26, 'Food - Snacks', 2.99);
insert into Products (id, title, price) values (27, 'Food - Frozen Meals', 8.49);
insert into Products (id, title, price) values (28, 'Accessories', 19.99);
insert into Products (id, title, price) values (29, 'Food - Beverages', 2.49);
insert into Products (id, title, price) values (30, 'Kitchen', 24.99);
insert into Products (id, title, price) values (31, 'Food', 29.99);
insert into Products (id, title, price) values (32, 'Food - Breakfast', 3.99);
insert into Products (id, title, price) values (33, 'Food - Beverages', 5.29);
insert into Products (id, title, price) values (34, 'Food - Soups', 2.99);
insert into Products (id, title, price) values (35, 'Food - Confectionery', 1.29);
insert into Products (id, title, price) values (36, 'Food - Cooking Kits', 9.99);
insert into Products (id, title, price) values (37, 'Office', 29.99);
insert into Products (id, title, price) values (38, 'Home', 29.99);
insert into Products (id, title, price) values (39, 'Audio', 39.99);
insert into Products (id, title, price) values (40, 'Food - Spices', 4.99);
insert into Products (id, title, price) values (41, 'Kitchen', 29.99);
insert into Products (id, title, price) values (42, 'Food - Dairy', 3.49);
insert into Products (id, title, price) values (43, 'Food - Soups', 4.29);
insert into Products (id, title, price) values (44, 'Food - Condiments', 2.99);
insert into Products (id, title, price) values (45, 'Music', 39.99);
insert into Products (id, title, price) values (46, 'Food - Bakery', 3.99);
insert into Products (id, title, price) values (47, 'Food - Cereal', 4.99);
insert into Products (id, title, price) values (48, 'Food - Dairy Alternatives', 1.99);
insert into Products (id, title, price) values (49, 'Toys', 22.99);
insert into Products (id, title, price) values (50, 'Accessories', 29.99);
insert into Products (id, title, price) values (51, 'Food - Breakfast', 4.29);
insert into Products (id, title, price) values (52, 'Pets', 12.99);
insert into Products (id, title, price) values (53, 'Garden', 22.99);
insert into Products (id, title, price) values (54, 'Food - Prepared Foods', 3.99);
insert into Products (id, title, price) values (55, 'Food - Canned Goods', 2.29);
insert into Products (id, title, price) values (56, 'Food - Prepared Foods', 3.99);
insert into Products (id, title, price) values (57, 'Food - Condiments', 3.49);
insert into Products (id, title, price) values (58, 'Food - Prepared Meals', 1.29);
insert into Products (id, title, price) values (59, 'Clothing - Outerwear', 49.99);
insert into Products (id, title, price) values (60, 'Health', 199.99);
insert into Products (id, title, price) values (61, 'Home', 18.99);
insert into Products (id, title, price) values (62, 'Electronics', 129.99);
insert into Products (id, title, price) values (63, 'Storage', 129.99);
insert into Products (id, title, price) values (64, 'Food - Frozen Foods', 3.99);
insert into Products (id, title, price) values (65, 'Garden', 24.99);
insert into Products (id, title, price) values (66, 'Home', 24.99);
insert into Products (id, title, price) values (67, 'Food - Snacks', 4.99);
insert into Products (id, title, price) values (68, 'Food - Snacks', 2.49);
insert into Products (id, title, price) values (69, 'Health', 39.99);
insert into Products (id, title, price) values (70, 'Audio', 129.99);
insert into Products (id, title, price) values (71, 'Food - Vegetables', 1.29);
insert into Products (id, title, price) values (72, 'Food - Grains', 2.99);
insert into Products (id, title, price) values (73, 'Kitchen', 29.99);
insert into Products (id, title, price) values (74, 'Food - Snacks', 2.99);
insert into Products (id, title, price) values (75, 'Food - Bakery', 4.49);
insert into Products (id, title, price) values (76, 'Food - Condiments', 3.99);
insert into Products (id, title, price) values (77, 'Food - Frozen Foods', 5.99);
insert into Products (id, title, price) values (78, 'Food - Bakery', 3.49);
insert into Products (id, title, price) values (79, 'Automotive', 49.99);
insert into Products (id, title, price) values (80, 'Health', 49.95);
insert into Products (id, title, price) values (81, 'Food - Condiments', 3.99);
insert into Products (id, title, price) values (82, 'Food - Dairy', 5.49);
insert into Products (id, title, price) values (83, 'Beauty', 25);
insert into Products (id, title, price) values (84, 'Clothing - Tops', 34.99);
insert into Products (id, title, price) values (85, 'Fitness', 34.99);
insert into Products (id, title, price) values (86, 'Home', 24.99);
insert into Products (id, title, price) values (87, 'Food - Snacks', 1.99);
insert into Products (id, title, price) values (88, 'Food - Oils & Vinegars', 3.99);
insert into Products (id, title, price) values (89, 'Pets', 59.99);
insert into Products (id, title, price) values (90, 'Food - Frozen', 6.49);
insert into Products (id, title, price) values (91, 'Food - Frozen Desserts', 4.99);
insert into Products (id, title, price) values (92, 'Food - Beverages', 1.99);
insert into Products (id, title, price) values (93, 'Pets', 12.99);
insert into Products (id, title, price) values (94, 'Food - Snacks', 2.99);
insert into Products (id, title, price) values (95, 'Food - Bakery', 3.99);
insert into Products (id, title, price) values (96, 'Clothing - Activewear', 29.99);
insert into Products (id, title, price) values (97, 'Food - Snacks', 2.49);
insert into Products (id, title, price) values (98, 'Home Appliances', 299.99);
insert into Products (id, title, price) values (99, 'Garden', 19.99);
insert into Products (id, title, price) values (100, 'Pets', 5.99);
